# Generated by Django 5.2.3 on 2025-09-11 10:37

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(flags=re.RegexFlag['UNICODE'], message='Full Name must contain only letters and spaces (no digits or symbols).', regex='^[^\\W\\d_]+(?: [^\\W\\d_]+)*$')]),
        ),
    ]
