# Generated by Django 5.2.3 on 2025-09-20 13:52

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(flags=re.RegexFlag['UNICODE'], message='Full Name must contain only letters and spaces (no digits or symbols).', regex='^[^\\W\\d_]+(?: [^\\W\\d_]+)*$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
