# Generated by Django 5.2.3 on 2025-07-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
