# Generated by Django 5.2.3 on 2025-09-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_item_latitude_item_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
