# Generated by Django 4.2.10 on 2025-09-14 12:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_item_item_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity_date', models.DateTimeField()),
                ('duration_hours', models.PositiveIntegerField(default=1)),
                ('max_participants', models.PositiveIntegerField(default=1)),
                ('requirements', models.TextField(blank=True)),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='donations.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.activity')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.recipient')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.volunteer')),
            ],
        ),
    ]
