# Generated by Django 5.2.7 on 2025-10-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_activity_volunteeractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteeractivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='item',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='volunteeractivity',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='volunteeractivity',
            name='volunteer',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Recipient',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
        migrations.DeleteModel(
            name='VolunteerActivity',
        ),
    ]
